# Generated by Django 5.0.6 on 2024-06-13 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afri_food', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponmobypiece',
            old_name='price_per_piece',
            new_name='price',
        ),
    ]
