# Generated by Django 4.0.6 on 2024-07-31 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afri_food', '0005_rename_price_per_piece_ponmobypiece_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ponmobypiece',
            options={'verbose_name': 'Others', 'verbose_name_plural': 'Others'},
        ),
    ]
